name: CI Docker

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image for result
        run: docker build ./result/ --file ./result/Dockerfile --tag timothedepoorter/result

      - name: Build the Docker image for vote
        run: docker build ./vote/ --file ./vote/Dockerfile --tag timothedepoorter/vote

      - name: Build the Docker image for worker
        run: docker build ./worker/ --file ./worker/Dockerfile --tag timothedepoorter/worker

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push result image to Docker Hub
        run: docker push timothedepoorter/result