name: CI Docker

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image for result
        run: docker build ./result --file Dockerfile --tag result:$(date +%s)