name: CI Docker

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image for result
        run: docker build ./result/ --file ./result/Dockerfile --tag result:$(date +%s)

      - name: Build the Docker image for vote
        run: docker build ./vote/ --file ./vote/Dockerfile --tag vote:$(date +%s)

      - name: Build the Docker image for worker
        run: docker build ./worker/ --file ./worker/Dockerfile --tag worker:$(date +%s)